apiVersion: v2
name: external-secrets
version: 6.1.0
type: application
dependencies:
  - name: kubernetes-external-secrets
    version: 6.1.0
    repository: "https://external-secrets.github.io/kubernetes-external-secrets"