apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-docker-credentials
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  source:
    path: vault/manifests/docker
    repoURL: https://github.com/awiesner4/argo-gs.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true