apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: node-autoscaler
value: 1000000
globalDefault: false
description: "Highest priority for node autoscaler pods"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: critical
value: 900000
globalDefault: false
description: "Critical observability components"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: identity
value: 800000
globalDefault: false
description: "Critical identity components"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: default
value: 0
globalDefault: true
description: "Default priority class"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: spaceholder
value: -100000
globalDefault: false
