apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  project: default
  source:
    path: charts/external-dns
    helm:
      valueFiles:
        - values.yaml
    repoURL: https://github.com/awiesner4/argo-gs.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true