apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-3"

---

apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "-3"

---

apiVersion: v1
kind: Namespace
metadata:
  name: al-is-awesome
  annotations:
    argocd.argoproj.io/sync-wave: "-3"

---

apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  annotations:
    argocd.argoproj.io/sync-wave: "-3"