apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-kubed
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  source:
    chart: kubed
    repoURL: https://charts.appscode.com/stable/
    targetRevision: v0.12.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true